package pojos;

import com.google.gson.JsonObject;

/**
 * The {@code Doctor} class represents a medical professional entity from the Patient's point of view.
 * A {@code Doctor} object encapsulates the necessary information to:
 * <ul>
 *     <li> The unique identifier generated by the database </li>
 *     <li> The doctor's name and surname </li>
 *     <li> The doctor's contact information (phone number) </li>
 *     <li> The doctor's email address </li>
 *     <li> The department the doctor works in</li>
 *     <li> The medical speciality of the doctor</li>
 * </ul>
 * <p>
 *     Instances of this class can be created either manually by the application or automatically
 *     reconstructed from database queries or from JSON files received over the network. Conversion utilities
 *     are provided inside the class {@link #fromJason(JsonObject)}
 * </p>
 *
 *<p>
 *     An important point to consider is that certain field values will be validated externally when
 *     necessary (e.g., email) for correctness before being assigned to a {@code Doctor}
 *</p>
 *
 * @author MamenCortes
 */
public class Doctor {

    private Integer id;
    private String name;
    private String surname;
    private String email;
    private Integer phone;
    private String department;
    private String speciality;


    /**
     * Creates a {@code Doctor} instance with most field values specified.
     *
     * @param name      the doctor's name
     * @param surname   the doctor's surname
     * @param email     the doctor's email address
     * @param phone     the doctor's contact information
     * @param department    the department in which the doctor works
     */
    public Doctor(String name, String surname, String email, Integer phone, String department) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.phone = phone;
        this.department = department;
        this.speciality = department;
        this.id = 0;
    }

    /**
     * Creates a default {@code Doctor} instance with most of the field values empty. This is typically
     * used when wanting to create a random Doctor that only has a phone number or when an empty instance
     * is desired and then fill it later.
     */
    public Doctor() {
        this.name = "";
        this.surname = "";
        this.email = "";
        this.phone = 123456789;
        this.department = "";
        this.speciality = "";
        this.id = 0;
    }

    @Override
    public String toString() {
        return "Doctor{" +
                "name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", email='" + email + '\'' +
                ", phone=" + phone +
                ", address='" + department + '\'' +
                '}';
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getPhone() {
        return phone;
    }

    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getSpeciality() {
        return speciality;
    }

    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * Converts this {@code Doctor} into a {@link JsonObject}. The JSON object specifies all public fields.
     *
     * @return  a JSON representation of this doctor
     *
     * @see JsonObject
     */
    public static Doctor fromJason(JsonObject json) {
        Doctor doctor = new Doctor();
        doctor.setId(json.get("id").getAsInt());
        doctor.setName(json.get("name").getAsString());
        doctor.setSurname(json.get("surname").getAsString());
        doctor.setPhone(json.get("contact").getAsInt());
        doctor.setEmail(json.get("email").getAsString());
        doctor.setDepartment(json.get("department").getAsString());
        doctor.setSpeciality(json.get("speciality").getAsString());
        return doctor;
    }

    /**
     * Converts this {@code Doctor} into a {@link JsonObject}. The JSON object specifies all public fields
     * except the {@code active} field //TODO: por que no lo especifica?
     *
     * @return  a JSON representation of this doctor
     *
     * @see JsonObject
     */
    public JsonObject toJason() {
        JsonObject json = new JsonObject();
        json.addProperty("id", id);
        json.addProperty("name", name);
        json.addProperty("surname", surname);
        json.addProperty("contact", phone);
        json.addProperty("email", email);
        json.addProperty("department", department);
        json.addProperty("speciality", speciality);
        return json;
    }

    /**
     * Utility method to verify if the {@code Doctor} object is empty or has specific values
     * //TODO: por que este metodo?
     *
     * @return
     */
    public Boolean isEmpty(){
        if(name.equals("")&&surname.equals("")&&email.equals("")&&phone == 123456789&&department.equals("")&&speciality.equals("")){
            return true;
        }
        return false;
    }
}
