package pojos;

/**
 * The {@code User} class represents a specific user.
 * A {@code User} object encapsulates the necessary information required to determine an access level or permissions
 * within the telemedicine server. This class encapsulates:
 * <ul>
 *     <li> The unique identifier generated by the database by auto-increment </li>
 *     <li> The user's email address</li>
 *     <li> The user's password</li>
 *     <li> The user's role</li>
 * </ul>
 *
 * <p>
 *     Additionally, the password will be encrypted to ensure security.
 * </p>
 *
 * @author MamenCortes
 */
public class User {

    private int id;
    private String email;
    private String password;
    private String role;

    /**
     * Creates an empty {@code User} instance.
     */
    public User() {}

    /**
     * Creates a complete {@code User} instance specifying all its field values.
     *
     * @param id        the user's unique identifier
     * @param email     the user's email address
     * @param password  the user's password
     * @param role      the user's role
     */
    public User(int id, String email, String password, String role) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.role = role;
    }


    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", role='" + role + '\'' +
                '}';
    }
}
